spring:
  application:
    name: data-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections:
    packages:
      trust-all: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 0 # random free port
