logging:
  level:
    org.example.servicerest: DEBUG

spring:
  application:
    name: rest-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
    packages:
      trust-all: true

server:
  port: 8080